const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const LESSON_TITLES=['Clear introductions','Daily routines','Pronunciation awareness','Food choices and descriptions','Families and personality','Meeting people naturally','Money and priorities','Life changes and decisions','Driving, travel, and rules','Comparing behaviour','Reconnecting with old friends','Manners and calm responses','Ability and effort','Education and learning methods','Working at something new','Shopping and problem-solving','Making plans and predictions','Describing places clearly','Health, habits, and advice','Technology in daily life','News and reliable information','Mysteries and deduction','People who influence us','Professional self-introduction','Handling a client conversation','Clarifying instructions','Explaining a process','Giving balanced opinions','Monthly review','Final reassessment and next plan'];
const TOPICS=['introducing yourself','your daily routine','clear pronunciation','food and meals','family and personality','first meetings','money and value','a recent life change','travel in your area','careful comparisons','meeting an old friend','polite behaviour','a skill you developed','effective study methods','your ideal workday','a shopping problem','next month’s plans','a place you recommend','healthy habits','how an app works','summarising news carefully','a harmless mystery','someone who influenced you','your professional background','an unclear client request','confirming scope and deadlines','explaining a workflow','giving a balanced opinion','your progress this month','your next learning priorities'];
const QUIZZES=[
['Which introduction is natural?',['My name is Ravi and I work in automation.','Myself Ravi working automation.','I am name Ravi.'],0,'Use “My name is…” or “I’m…” for a natural introduction.'],
['Which sentence describes a routine?',['I usually study in the morning.','I am usually study morning.','I studied every morning now.'],0,'Use the present simple for routines.'],
['Which habit improves pronunciation?',['Listening and repeating short phrases.','Speaking faster than the audio.','Ignoring word stress.'],0,'Focused listening and repetition improve sound awareness.']
];
const genericQuiz=(i)=>[
`Which sentence is the clearest choice for ${TOPICS[i]}?`,
[`I can explain this clearly with one concrete example.`,`I explaining this very clear yesterday now.`,`This topic explain by me good.`],0,
'Clear English usually uses a complete subject–verb structure and a concrete example.'
];
const COURSE_LESSONS=LESSON_TITLES.map((title,i)=>{const q=QUIZZES[i]||genericQuiz(i);return{id:`day-${String(i+1).padStart(2,'0')}`,day:i+1,title,focus:['speaking','grammar','vocabulary','reflection'],sources:['Personalized English practice','Local course references'],steps:[
{id:'warmup',type:'prompt',title:'Speak first',label:'NO SCRIPT',body:`Speak for 30–60 seconds about ${TOPICS[i]}. Use one real example.`},
{id:'language',type:'quiz',title:'Language check',label:'QUICK CHECK',body:'Choose the clearest sentence.',question:q[0],choices:q[1],answer:q[2],explanation:q[3]},
{id:'vocabulary',type:'text',title:'Active language',label:'WRITE THEN SAY',body:`Write four useful phrases connected with ${TOPICS[i]}, then say one true sentence with each.`,placeholder:'Write your phrases and examples here.'},
{id:'practice',type:'prompt',title:'Practical response',label:'REAL LIFE',body:`Give a structured response about ${TOPICS[i]}: main point, example, and conclusion.`},
{id:'speaking-check',type:'record',title:'Speaking task',label:'RECORD YOURSELF',body:`Record a one-minute response about ${TOPICS[i]}. Focus on clarity and natural pauses.`}
]}});
let activeLessonIndex=Number(localStorage.getItem('em_active_lesson')||0);activeLessonIndex=Math.min(Math.max(activeLessonIndex,0),29);let LESSON=COURSE_LESSONS[activeLessonIndex];let state={step:0,completed:{},answers:{}};let recorder=null,chunks=[];
const screenNames={dashboard:'Dashboard',course:'Course',diagnostic:'Diagnostic',lesson:'Lesson',progress:'Progress',library:'Library',settings:'Settings','device-test':'Device Test'};
function showScreen(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.go===name));$('#screenTitle').textContent=screenNames[name]||'English Mastery';window.scrollTo({top:0,behavior:'smooth'});if(name==='progress')renderProgress();}
async function loadLesson(index=activeLessonIndex){activeLessonIndex=Math.min(Math.max(Number(index)||0,0),29);localStorage.setItem('em_active_lesson',activeLessonIndex);LESSON=COURSE_LESSONS[activeLessonIndex];const saved=await EMDB.get('progress',LESSON.id);state={step:Math.min(Math.max(Number(saved?.currentStep)||0,0),4),completed:saved?.completed||{},answers:{}};const grammar=await EMDB.get('answers',LESSON.id+':grammar');if(grammar)state.answers.grammar=grammar.value;renderLesson();updateDashboard();}
async function saveProgress(){await EMDB.put('progress',{id:LESSON.id,currentStep:state.step,completed:state.completed,updatedAt:new Date().toISOString()});$('#globalSaveStatus').textContent='Saved automatically';updateDashboard();}
function renderCatalog(){$('#lessonCatalog').innerHTML=COURSE_LESSONS.map((l,i)=>`<div class="module-card"><div><span class="module-no">DAY ${l.day}</span><h3>${l.title}</h3><p>${TOPICS[i]}</p></div><button class="secondary open-lesson" data-lesson-index="${i}">${i===activeLessonIndex?'Continue':'Open'}</button></div>`).join('');$$('.open-lesson').forEach(b=>b.onclick=async()=>{await loadLesson(b.dataset.lessonIndex);showScreen('lesson')});}
function renderPath(){$('#pathList').innerHTML=LESSON.steps.map((s,i)=>`<div class="lesson-row ${state.completed[s.id]?'complete':i===state.step?'current':''}"><span>${state.completed[s.id]?'✓':i+1}</span><div><b>${s.title}</b><small>${s.label}</small></div><em>${i===state.step?'Current':''}</em></div>`).join('');}
function renderLesson(){const s=LESSON.steps[state.step];$('#stepCounter').textContent=`Day ${LESSON.day} · Step ${state.step+1} of 5`;$('#lessonTitle').textContent=LESSON.title;$('#lessonProgress').style.width=`${(state.step+1)*20}%`;let h=`<span class="tag">${s.label}</span><h3>${s.title}</h3><p>${s.body}</p>`;
if(s.type==='prompt')h+=`<div class="tip-box"><b>Task:</b> ${s.body}</div>`;
if(s.type==='quiz')h+=`<div class="choice-list">${s.choices.map((c,i)=>`<button class="choice ${state.answers.grammar===i?'selected':''}" data-choice="${i}">${c}</button>`).join('')}</div><button class="primary" id="checkQuiz">Check answer</button><div id="quizFeedback"></div>`;
if(s.type==='text')h+=`<label class="field-label">Your answer</label><textarea id="activeText" placeholder="${s.placeholder||''}"></textarea>`;
if(s.type==='record')h+=`<div class="recording-box"><div class="recording-controls"><button class="primary" id="recordBtn">Start recording</button><button class="secondary" id="stopRecordBtn" disabled>Stop</button></div><div class="recording-status" id="recordStatus">Microphone permission is requested only when you start.</div><audio id="recordPlayback" controls hidden></audio></div>`;
h+=`<label class="step-complete"><input id="doneBtn" type="checkbox" ${state.completed[s.id]?'checked':''}> Mark this step complete</label>`;$('#stepHost').innerHTML=h;$('#prevStep').disabled=state.step===0;$('#nextStep').textContent=state.step===4?'Finish':'Next';bindStep(s);renderPath();}
function bindStep(s){$('#doneBtn').onchange=async e=>{state.completed[s.id]=e.target.checked;await saveProgress();renderPath()};if(s.type==='quiz'){$$('.choice').forEach(b=>b.onclick=()=>{state.answers.grammar=Number(b.dataset.choice);$$('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});$('#checkQuiz').onclick=async()=>{if(state.answers.grammar===undefined)return;const ok=state.answers.grammar===s.answer;$('#quizFeedback').innerHTML=`<div class="feedback ${ok?'ok':'bad'}"><b>${ok?'Correct':'Try again'}</b><br>${s.explanation}</div>`;await EMDB.put('answers',{id:LESSON.id+':grammar',value:state.answers.grammar});await EMDB.put('attempts',{id:LESSON.id+':'+Date.now(),lessonId:LESSON.id,correct:ok,createdAt:new Date().toISOString()});}}if(s.type==='text'){EMDB.get('answers',LESSON.id+':vocabulary').then(x=>{if(x)$('#activeText').value=x.value||''});let timer;$('#activeText').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>EMDB.put('answers',{id:LESSON.id+':vocabulary',value:e.target.value,updatedAt:new Date().toISOString()}),350)}}if(s.type==='record')bindRecording();}
function bindRecording(){const start=$('#recordBtn'),stop=$('#stopRecordBtn'),status=$('#recordStatus'),play=$('#recordPlayback');start.onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});play.src=URL.createObjectURL(blob);play.hidden=false;status.textContent='Recording saved for this session.';stream.getTracks().forEach(t=>t.stop());await EMDB.put('recordings',{id:LESSON.id+':speaking-check',createdAt:new Date().toISOString(),size:blob.size,type:blob.type,blob})};recorder.start();start.disabled=true;stop.disabled=false;status.textContent='Recording…'}catch(e){status.textContent='Microphone unavailable: '+e.message}};stop.onclick=()=>{if(recorder?.state==='recording')recorder.stop();start.disabled=false;stop.disabled=true};}
$('#prevStep').onclick=async()=>{if(state.step>0){state.step--;await saveProgress();renderLesson()}};$('#nextStep').onclick=async()=>{if(state.step<4){state.step++;await saveProgress();renderLesson()}else{state.completed[LESSON.steps[4].id]=true;await saveProgress();showScreen('progress')}};
function updateDashboard(){const done=Object.values(state.completed).filter(Boolean).length;$('#completedCount').textContent=done;$('#coursePercent').textContent=`${done*20}%`;$('#progressPercent').textContent=`${done*20}%`;$('#progressBar').style.width=`${done*20}%`;$('#resumeLabel').textContent=`Day ${LESSON.day} · Step ${state.step+1}`;$('.hero-card h2').textContent=`Day ${LESSON.day} · ${LESSON.title}`;renderPath();}
async function renderProgress(){const attempts=await EMDB.getAll('attempts');const lessonAttempts=attempts.filter(a=>a.lessonId===LESSON.id);const correct=lessonAttempts.filter(a=>a.correct).length;$('#answerScore').textContent=lessonAttempts.length?`${correct}/${lessonAttempts.length}`:'—';$('#attemptList').innerHTML=lessonAttempts.length?lessonAttempts.slice(-10).reverse().map(a=>`<div class="attempt-item"><div><b>${a.correct?'Correct':'Incorrect'} answer</b><small>${new Date(a.createdAt).toLocaleString()}</small></div><span>${a.correct?'✓':'!'}</span></div>`).join(''):'No attempts yet.';}
const DIAG=[['Grammar','Choose the correct sentence.',['I have lived here for five years.','I live here since five years.'],0],['Vocabulary','Choose the natural phrase.',['make a decision','do a decision'],0],['Confidence','How comfortable are you speaking without notes?',['1','2','3','4','5'],2]];let diagStep=0,diagAnswers={};function renderDiagnostic(){const d=DIAG[diagStep];$('#diagCounter').textContent=`Question ${diagStep+1} of ${DIAG.length}`;$('#diagTitle').textContent=d[0];$('#diagProgress').style.width=`${((diagStep+1)/DIAG.length)*100}%`;$('#diagHost').innerHTML=`<h3>${d[1]}</h3><div class="choice-list">${d[2].map((x,i)=>`<button class="diagnostic-option ${diagAnswers[diagStep]===i?'selected':''}" data-diag="${i}">${x}</button>`).join('')}</div>`;$$('[data-diag]').forEach(b=>b.onclick=()=>{diagAnswers[diagStep]=Number(b.dataset.diag);renderDiagnostic()});$('#diagPrev').disabled=diagStep===0;$('#diagNext').textContent=diagStep===DIAG.length-1?'Finish':'Next';}
$('#diagPrev').onclick=()=>{if(diagStep>0){diagStep--;renderDiagnostic()}};$('#diagNext').onclick=async()=>{if(diagAnswers[diagStep]===undefined)return;if(diagStep<DIAG.length-1){diagStep++;renderDiagnostic()}else{await EMDB.put('meta',{id:'diagnostic',answers:diagAnswers,completedAt:new Date().toISOString()});$('#skillProfile').innerHTML='<div class="priority-card"><strong>Personal priority</strong><small>Build fluency through daily speaking, active vocabulary, and review.</small></div>';showScreen('course')}};$('#startDiagnostic').onclick=()=>{diagStep=0;renderDiagnostic();showScreen('diagnostic')};
async function exportProgress(){const data=await EMDB.exportAll();const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='english-mastery-stage16-backup.json';a.click();URL.revokeObjectURL(u)}
$('#exportBtn').onclick=exportProgress;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;await EMDB.importAll(JSON.parse(await f.text()));await loadLesson();alert('Progress imported.')};$('#diagnosticsBtn').onclick=()=>{const data={version:'16.0.0',time:new Date().toISOString(),userAgent:navigator.userAgent,health:localStorage.getItem('em_last_health_check'),errors:localStorage.getItem('em_error_logs')};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='english-mastery-diagnostics.json';a.click();URL.revokeObjectURL(u)};$('#resetBtn').onclick=async()=>{if(!confirm('Reset all learning progress?'))return;for(const s of ['progress','answers','attempts','recordings','meta'])await EMDB.clear(s);localStorage.removeItem('em_active_lesson');location.reload()};
$$('[data-go]').forEach(b=>b.onclick=async()=>{const name=b.dataset.go;if(name==='lesson')await loadLesson();showScreen(name)});$('#themeBtn').onclick=()=>document.body.classList.toggle('light');window.addEventListener('online',network);window.addEventListener('offline',network);function network(){$('#networkBadge').textContent=navigator.onLine?'Online':'Offline';$('#networkBadge').classList.toggle('offline',!navigator.onLine)}
(async()=>{await EMDB.open();network();$('#storageBadge').textContent='Auto-save ready';renderCatalog();await loadLesson();showScreen('dashboard')})();
